[project]
name = "unitree-go2-realtime-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.1",
    "livekit-agents[openai,silero,turn-detector]~=1.2",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.38.0",
]
